package org.usfirst.frc620.Warbots2015;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.RobotDrive.MotorType;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import java.util.Vector;

import org.usfirst.frc620.Warbots2015.subsystems.GyroITG3200;

import com.kauailabs.navx_mxp.AHRS;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    public static Jaguar driveTrainPWMJagRL;
    public static Jaguar driveTrainPWMJagRR;
    public static Jaguar driveTrainPWMJagFL;
    public static Jaguar driveTrainPWMJagFR;

    public static CANTalon driveTrainCANTalonRL;
    public static CANTalon driveTrainCANTalonFR;
    public static CANTalon driveTrainCANTalonRR;
    public static CANTalon driveTrainCANTalonFL;
    
//    public static Gyro driveTrainGyro;
//    public static GyroITG3200 driveTrainGyro3200;
    public static AHRS imu;
	public static SerialPort serialPort;

    
    
    public static DigitalInput pickerlimitSwitchBottom;
    public static DigitalInput pickerlimitSwitchTop;
    
    public static RobotDrive driveTrainRobotDrive;
    
    public static Compressor pneumaticsCompressor;
    public static Solenoid pneumaticsSolenoid; 
    
    public static Talon pickerPickerMotor;

    public static void init() {
    	
    	Boolean JaguarIsPresent = (driveTrainCANTalonRL == null); 

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    	//unused drive train
    	driveTrainPWMJagRL = new Jaguar(1);
        LiveWindow.addActuator("DriveTrain", "PWMJagRL", (Jaguar) driveTrainPWMJagRL);
        
        driveTrainPWMJagRR = new Jaguar(4);
        LiveWindow.addActuator("DriveTrain", "PWMJagRR", (Jaguar) driveTrainPWMJagRR);
        
        driveTrainPWMJagFL = new Jaguar(2);
        LiveWindow.addActuator("DriveTrain", "PWMJagFL", (Jaguar) driveTrainPWMJagFL);
        
        driveTrainPWMJagFR = new Jaguar(3);
        LiveWindow.addActuator("DriveTrain", "PWMJagFR", (Jaguar) driveTrainPWMJagFR);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainPWMJagFL, driveTrainPWMJagRL,
              driveTrainPWMJagFR, driveTrainPWMJagRR);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        //gyro
        try {
			serialPort = new SerialPort(57600, SerialPort.Port.kMXP);
			byte update_rate_hz = 50;
			imu = new AHRS(serialPort, update_rate_hz);
		} catch (Exception ex) {

		}
		if (imu != null) {
			LiveWindow.addSensor("IMU", "Gyro", imu);
		}
        
        //picker motor
        pickerPickerMotor = new Talon(0);
        LiveWindow.addActuator("Picker", "PickerMotor", (Talon) pickerPickerMotor);
        
        //limit switches
        pickerlimitSwitchTop = new DigitalInput(1);
        LiveWindow.addSensor("Picker", "limitSwitchTop", pickerlimitSwitchTop);

        pickerlimitSwitchBottom = new DigitalInput(0);
        LiveWindow.addSensor("Picker", "limitSwitchBottom", pickerlimitSwitchBottom);
        
        //pneumatics
        pneumaticsCompressor = new Compressor(0);
        
        pneumaticsSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("Pneumatics", "Solenoid", pneumaticsSolenoid);
        

 
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        //actual drive train
        driveTrainRobotDrive = null;
        
        driveTrainCANTalonRL = new CANTalon(1);
        driveTrainCANTalonFL = new CANTalon(2);
        driveTrainCANTalonFR = new CANTalon(3);
        driveTrainCANTalonRR = new CANTalon(4);
        
       
        
//        driveTrainRobotDrive = new RobotDrive(driveTrainCANTalonFL, driveTrainCANTalonRL,
//                driveTrainCANTalonFR, driveTrainCANTalonRR);;
        
//        if(JaguarIsPresent) {
//        	driveTrainRobotDrive = new RobotDrive(
//             		driveTrainPWMJagFL, 
//             		driveTrainPWMJagRL,
//                    driveTrainPWMJagFR, 
//                    driveTrainPWMJagRR); 
//        }
//        else {
        	driveTrainRobotDrive = new RobotDrive(
           		 driveTrainCANTalonFL, 
           		 driveTrainCANTalonRL,
                 driveTrainCANTalonFR, 
                 driveTrainCANTalonRR);
        //}
        
        driveTrainRobotDrive.setInvertedMotor(MotorType.kFrontRight, true);
        driveTrainRobotDrive.setInvertedMotor(MotorType.kRearRight, true);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

    }
}
