package org.usfirst.frc620.Warbots2015.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc620.Warbots2015.Robot;
import org.usfirst.frc620.Warbots2015.RobotMap;

/**
 *
 */
public class  Drive extends Command {
	double time;
	
	double drivex = 0;
	double drivey = 0;
	double drivez = 0;
	double turn = 0;
	double theta = 90;
	
    public Drive() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public Drive(double t, double x, double y, double z) {
    	time = t;
    	drivex = x;
    	drivey = y;
    	drivez = z;
    	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    public Drive(double t,double angle) {
    	time = t;
    	
    	drivez = angle;
    	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    protected void initialize() {
    	setTimeout(time);
    }

    protected void execute() {
    	Robot.driveTrain.mecanumDrive(drivex, drivey, drivez, turn);
    	SmartDashboard.putNumber("angle", theta);
    	SmartDashboard.putData("Gyro", RobotMap.driveTrainGyro);
    }

    protected boolean isFinished() {
        return isTimedOut();
    }

    protected void end() {
    	Robot.driveTrain.mecanumDrive(0, 0, 0, 0);
    }

    protected void interrupted() {
    	end();
    }
}
