package org.usfirst.frc620.Warbots2015.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc620.Warbots2015.Robot;
import org.usfirst.frc620.Warbots2015.RobotMap;

public class  liftPicker extends Command {

	public liftPicker() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.picker);
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	protected void initialize() {
	}

	protected void execute() {
		Robot.picker.setSpeed(.3);
	}

	protected boolean isFinished() {
		return RobotMap.pickerlimitSwitchTop.get();
	}

	protected void end() {
	}

	protected void interrupted() {
	}
}
