package org.usfirst.frc620.Warbots2015.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc620.Warbots2015.Robot;
import org.usfirst.frc620.Warbots2015.RobotMap;

public class  liftPicker extends Command {
	
	double t = 100;
	public liftPicker() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.picker);
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}
	public liftPicker(double time){
		t = time;
	}

	protected void initialize() {
		setTimeout(t);
	}

	protected void execute() {
		Robot.picker.setSpeed(1);
	}

	protected boolean isFinished() {
		return RobotMap.pickerlimitSwitchTop.get()||isTimedOut();
	}

	protected void end() {
	}

	protected void interrupted() {
	}
}
